/**
 * Content negotiation for blog posts.
 *
 * A client that explicitly asks for `text/markdown` gets the plain-markdown
 * representation generated by `site-tools markdown all`; everyone else gets the
 * usual HTML page. Both live at the same URL, so a link an agent was given still
 * resolves for a human.
 *
 * The markdown is also addressable directly at /blog/<slug>.md, advertised through
 * a Link header, for clients that would rather not negotiate.
 */

const MARKDOWN_TYPES = ["text/markdown", "text/x-markdown"];

/**
 * Parse an Accept header into [{ type, q }], ignoring parameters other than q.
 */
function parseAccept(header) {
  if (!header) return [];

  return header
    .split(",")
    .map((part) => {
      const [type, ...params] = part.trim().split(";");
      let q = 1;

      for (const param of params) {
        const [key, value] = param.split("=").map((s) => s.trim());
        if (key === "q") {
          const parsed = Number.parseFloat(value);
          // A malformed q is treated as absent rather than as a rejection.
          if (Number.isFinite(parsed)) q = parsed;
        }
      }

      return { type: type.trim().toLowerCase(), q };
    })
    .filter((entry) => entry.type !== "");
}

/**
 * Highest q across the given exact media types. Wildcards deliberately do not
 * count: `*​/*` from curl or a browser must not be read as a request for markdown.
 */
function qualityFor(accepted, types) {
  let best = 0;
  for (const entry of accepted) {
    if (types.includes(entry.type) && entry.q > best) best = entry.q;
  }
  return best;
}

/**
 * Highest q that applies to HTML, wildcards included — a browser sending
 * `text/html,...,*​/*;q=0.8` is asking for HTML by any of those routes.
 */
function htmlQuality(accepted) {
  let best = 0;
  for (const entry of accepted) {
    const applies =
      entry.type === "text/html" || entry.type === "text/*" || entry.type === "*/*";
    if (applies && entry.q > best) best = entry.q;
  }
  return best;
}

export function prefersMarkdown(header) {
  const accepted = parseAccept(header);
  const md = qualityFor(accepted, MARKDOWN_TYPES);
  // Ties go to markdown: naming it explicitly alongside HTML is a deliberate signal.
  return md > 0 && md >= htmlQuality(accepted);
}

/**
 * Map a post URL to its markdown asset. Returns null for anything that is not a
 * single post — the listing page, pagers, and the .md files themselves.
 */
export function markdownPathFor(pathname) {
  if (pathname.endsWith(".md")) return null;

  const match = pathname.match(/^\/blog\/([^/]+)\/?$/);
  if (!match) return null;

  const slug = match[1];
  if (slug === "page") return null;

  return `/blog/${slug}.md`;
}

export async function onRequest(context) {
  const { request, next, env } = context;
  const url = new URL(request.url);

  const mdPath = markdownPathFor(url.pathname);
  if (!mdPath || (request.method !== "GET" && request.method !== "HEAD")) {
    return next();
  }

  const mdUrl = new URL(mdPath, url.origin);

  if (prefersMarkdown(request.headers.get("Accept"))) {
    const asset = await env.ASSETS.fetch(new Request(mdUrl, { method: "GET" }));

    // No generated markdown (a draft, or a page this does not cover): fall back to
    // HTML rather than turning a live page into a 404.
    if (asset.ok) {
      const headers = new Headers(asset.headers);
      headers.set("Content-Type", "text/markdown; charset=utf-8");
      headers.set("Vary", "Accept");
      headers.set("Link", `<${url.href}>; rel="canonical"`);

      return new Response(request.method === "HEAD" ? null : asset.body, {
        status: 200,
        headers,
      });
    }
  }

  // Vary must be set on the HTML response too, or a cache can hand a stored HTML
  // body to a client that asked for markdown.
  const response = await next();
  const headers = new Headers(response.headers);
  headers.append("Vary", "Accept");
  headers.set("Link", `<${mdUrl.href}>; rel="alternate"; type="text/markdown"`);

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}
